import type { Metadata } from 'next'
import './globals.css'
import ThemeProvider from '@/components/ThemeProvider/ThemeProvider'

export const metadata: Metadata = {
	title: 'Kanban',
	description: 'Generated by create next app kanban for time management',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<ThemeProvider>{children}</ThemeProvider>
			</body>
		</html>
	)
}
