import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
	title: 'Kanban',
	description: 'Generated by create next app kanban for time management',
}

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='en'
			className={`${inter.className} overflow-hidden w-screen bg-slate-200`}>
			<body className='h-screen bg-slate-200 w-screen'>{children}</body>
		</html>
	)
}
